version: "3.3"

services:
  node-media-server:
    image: illuspas/node-media-server
    container_name: node-media-server
    restart: always
    ports:
      - "1936:1935"
      - "8001:8000"
    volumes:
      - /volume1/docker/node-media-server/config:/app/config
      - /volume1/docker/node-media-server/www:/app/www
      - /volume1/docker/node-media-server/media:/app/media
